import MultiStepForm from '@/src/components/form/MultiStepForm'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<section style={{maxWidth: '960px', minWidth: '960px', margin: 'auto'}}>
				<MultiStepForm />
			</section>
    </>
  )
}
